def patternToNumber(pattern):
	if len(pattern) == 0:
		return 0
	return 4 * patternToNumber(pattern[0:-1]) + symbolToNumber(pattern[-1:])

def symbolToNumber(symbol):
	if symbol == "A":
		return 0
	if symbol == "C":
		return 1
	if symbol == "G":
		return 2
	if symbol == "T":
		return 3

def numberToPattern(x, k):
	if k == 1:
		return numberToSymbol(x)
	return numberToPattern(x // 4, k-1) + numberToSymbol(x % 4)

def numberToSymbol(x):
	if x == 0:
		return "A"
	if x == 1:
		return "C"
	if x == 2:
		return "G"
	if x == 3:
		return "T"

k = 50
text = "AATCACCCCATTTTCGGTACTACTCAGCTCCAGGTCTGAACGGTTTACACCTGCCGCACTCTGGCAGGTCATAACTCATTGCAGTCTGGCATAAATGTCGATGCCTATTAGTTTTAATCGGTTTCTCTTGAGCGCGAGTCATGGAAACCGGCACTAAACGTCCAAGGCCCACCGTAACCGGCACTCAGAGAATGATACCTTGAGCCTGAGCCCGTCTTACCCTGACACGCGAGTTTAGCATTCCCACAGCAGAAGTCATGAGACTCCACGAGAGACAATTGCAAGGGAATGGCCGCCGAGGTAAATCACAGACCATACTACATTAGGGGTTACAATTGGCCAACGGTCAAGTTGAGTAGAATTTCTCTTGCGTGGGGATGTATAAGTTTTTGAGCTTAGGTCGTAGGAGGCAAAGTGGCGCTTTAAAGAGAAAGATGCAATGATTGAGCGTTTCAGGCTAAGAGATGCTCAGGTATAACCGGATGAGTTCCATATCTCAAGCAGTAGAAAGGTATGAGCGTGTTACCGCGAAATTATTGTGCTGCCAACTAAGTGGGGGGCGTGTGTTTTACGGCCCCCCGATGAAGTCTACTGGAAGAGAATCCTCTGTAATTATCTGGTCGAACGCTGTGTGGACTATATCGGGGTCGTGAGTATTATCGCCATAGAGAACTTTCCGGCTCCTACTGAATAATATCTGACCTCTGCTTGGGAAGACTGGATTGTAAACTCACCCCTTTCTCCTCTTGAGGGCACTCGTCAAAGCTGCTCTAGAGTATATACCCCTGCGGTGCGTATGGCGTGCATGAACTGACGTGATCTGGCGCGGAGAATGCTTGGTAGGAACACTAACGACCTCAACGACGCGTACCGCGCCTTTATGCTAAGTGCGAGGTATCGCTGACGCGGGGCAATAGCCAAAAAAGCTGGATCATCTTTGATGCAGCATTTATATGCAAATTTTAATCGGGGATTTGGGCCAAGCCGTCCCTTGCCGAAT"
a = []
for i in range(len(text) - k+1):
	notIn = True
	for x in a:
		if x == text[i:i+k]:
			notIn = False
	if notIn:
		a.append(text[i:i+k])
for x in a:
	print(x)