reverse = {'A':4, 'C':2, 'D':2, 'E':2, 'F':2, 'G':4, 'H':2, 'I':3, 'K':2, 'L':6, 'M':1, 'N':2, 'P':4, 'Q':2, 'R':6, 'S':6, 'T':4, 'V':4, 'W':1, 'Y':2}

p = 'MWDSTPSRIHCPEASRMPTGWDEMVDLHHQHITIRPSTTRFECEICSMTLKQQVHSNVEQWPKFCSANNTQHGIPGMQEYFAINCNYDEFTMYYCAYPHSRARWRGVILLYQLSHMSQFEDIHGFHQMAKPDHNDCIFTHSTSQFAHEQVFQRLVQIKNNYTEQSNSFCPENHPDWAVMKTYRCKAHICYIVFGVTQSEFSPIMERNNVYCYIWFRWTPFMNCKQRLLAPGWKNHVAQYAGEKIYNYSQLNDADLICWRKAREDWQMYLQGMFENRTGPQCWYWHPEYPGWYIDLPWDWGHFYWVDHVSEYDYYELCQAGNNMHEHDMFREFCVYDTATKMSYLSADDAEMSNELAMTKTNQMSQVHSQCHPVTAECTWQVMLWTLMIKSPDCMYKEGTWSTAHWTCFQMCWAWPCEASRHTLMITYHGVFHLAYAIRYQHKLKECEAQKSCQLDKKQNMIVDDQIRGQDEPIASQYNEETQVNQMNNFKWQHWAMVTKAGWSNDGFWQHFHCKNSWGMKPEKNSAYWPMLYYDACVTYPNTIKSGGYTWPTCWSLQLNSEDNYHRCARYPRWNNCKDQLISNHVLPMCNAHCCEETILMTHGTWRDHFMNYMQVLNQGGWMEWYFAMDSFETDCPKFSEGTIFYSWQWKPTFMMFWGVDFFLMAMRIHYMLIYDPQQNGFRCEYVEYLRRFTQYKRASKIKFKKLCHDRYTPSWDNSKPAIAKNGLHCSNELSFNAPPERYHHSYMEDTWDTCSCIESNFYFLVLSEVWCYFFYYCAYGAIPSRKMFIQVFYFHFMRVMPSADMDIRYSFECIQASIPDFKRAKYWDDKLCVGCGFGFTGDLNNCQYSYIYLWAVRGGAFAEWNFLQSAEWDLWQEMEEENAFITGSLLCDQSTPRNRQCGEKVMSSLVPYFLFRFPTNLRYDFHVAMFKPCLCCLGFRIHMMDEQIMVDCSIERPDVTNAFARIIIVMHPCVQNYTFAGFAIYPSKQWYMNCKKWN'
poss = 1
for x in p:
	poss = (poss * reverse[x]) % 1000000
poss = (poss * 3) % 1000000

print(poss)
