import rna

dna = "TGAAACCGCTCTATGGATGACCCTCCCCTGAATATGATCTTTCGGTTTTATCCTCCGGAGCCGTTCCCTGGATGAGTAGACTAGCACGACTTCGTTTCGGGCAGTAATGTGCAGGTACAGTGAGTTGGTCTCACTGGTCGAGAATACGGACCGCTTAAACATCTGATAGCGGGCGGATAGCGCAAGACCCTGAATAGCACGCGGTGTATAGCTGGTTATCTTCAGTAACGAAGGTGCACCATTCGCGGTAAGCCTCTGGCCCGTATAAGTTCGTAAACTATATTGTCACACTTAATAGACACGTGAGGAACCTGGGTCACTTCGTTGATACAGTCAGGCAGGTTCTACGATATGCCTGCGTAGCTTGTTACACTGGTCCCGTCCCTGATGTGTGCAATCGGTGGCACTAATGATAACTTACGCGAGCTGGACGGGTTAGCTAACCCGTCCAGCTCGCGTAAGTTATCATCCAACACTCATACGGATGGGACATCTCGCTATAACAAAGAAAATTTCCGCCGAATGATGAACTCTTGTATAACAGGGCTTCCAGTTCGGGACTCCAGGGCCATCCACACCCCTTAAATCTTAGCTTCGTTTTCGCAAGTACTAGAAGTAAAGACCGAACCCTCGCAGTTCGACAACAGTGTGCTCAGGGACCTGGTATGACTCCCTTCTAGGCGGGGGCCCTTGGGAACGCCCGCAACACCTCTAGATTAGGATAGTGGACCACCGTCTATCAAATCGTAGGTCTCCCGATAAGTAGTAAGGGGGTTTTGGAGCATATGTCTCGGTCACAAGCTTGGTGAACTCAGAGTGGCCATTTCATTTGATAGCTTATTGGAGATACCCACTATTTGATCGGGTTCTGTACGTCA"
rnaForward = rna.transcribe(dna)
rnaBackwards = rna.reverseTranscribe(dna)
proteins = []
for i in range(len(rnaForward)):
    if rnaForward[i:i+3] == 'AUG':
        proteins.append(rna.protein(rnaForward[i:]))
for i in range(len(rnaBackwards)):
    if rnaBackwards[i:i+3] == 'AUG':
        proteins.append(rna.protein(rnaBackwards[i:]))

proteins = set(proteins)
for x in proteins:
    print(x)
